import {AppRouterCacheProvider} from '@mui/material-nextjs/v13-appRouter';

export const metadata = {
  title: 'Filter UI',
  description: 'Generated by Next.js',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body>
    <AppRouterCacheProvider>
      {children}
    </AppRouterCacheProvider>
    </body>
    </html>
  )
}
